apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: elastic-container
      image: elastic
      volumeMounts:
      - mountPath: "/var/lib/config"
        name: es-config-dir
  volumes:
    - name: es-config-dir
      secret:
        secretName: es-config-map