apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: elastic-container
      image: elastic
      volumeMounts:
      - mountPath: "/var/lib/secret"
        name: es-secret-dir
  volumes:
    - name: es-secret-dir
      secret:
        secretName: es-secret