apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-name
provisioner: kubernetes.io/aws-ebs  # Service Provider Specific
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4